# Generated by Django 2.2.16 on 2022-12-26 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_Ñfix_ingredient_amount_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveIntegerField(max_length=64, validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиентов должно быть больше ноля.')], verbose_name='Количество'),
        ),
    ]
